meta_product_name: "InLine"
meta_title: "InLine - Never wait in line again"
meta_description: "InLine digitizes all types of physical queues, such as the nerve-wracking airport line, the hypocondric line to the emergency room, and the depressing bank line. Because why waste your precious time with waiting in a physical line, when you can let a digital avatar do the waiting for you?"
meta_image: "inline-home-page.png"
